org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=26.2-SNAPSHOT
project.platforms=Common, Fabric, NeoForge
project.plugins=1.1-SNAPSHOT

mod.authors=Fuzs
mod.description=Lock your inventory slots. Protect your tools. Prevent accidents, fully client-side.
mod.group=fuzs.lockedinslots
mod.id=lockedinslots
mod.license=MPL-2.0
mod.name=Locked In Slots
mod.version=26.2.0

dependencies.fabric.fabricapi=required
dependencies.fabric.forgeconfigapiport=required
dependencies.fabric.puzzleslib=required
dependencies.neoforge.puzzleslib=required

distributions.curseforge.id=1563534
distributions.curseforge.slug=locked-in-slots
distributions.github.slug=locked-in-slots
distributions.modrinth.id=y2Xn63zs
distributions.modrinth.slug=locked-in-slots

environments.client=required
environments.server=unsupported
